### ISSUE TITLE
[Just Out of Curiosity] How do you generate Python scripts automatically from jupyter notebooks?

### ISSUE THREAD

**Issue by iCSawyer** [WM-SEMERU/CodeSyntaxConcept#17]
I came across some Python scripts, such as [this one](https://github.com/WM-SEMERU/CodeSyntaxConcept/blob/master/CodeSyntaxConcept/evaluator.py), and noticed they were generated by a Jupyter notebook. It appears that the conversion process involves more than just combining all cells, with commands like `#| hide` and `#| eval: false` being used.

I believe these techniques could be incredibly helpful for my programming. If it's not too much trouble, could you kindly share the techniques or tools you use? I would really appreciate it. Thank you so much!

**Comment by danielrcardenas** [comment]
Hello, we use nvdeb https://nbdev.fast.ai/tutorials/tutorial.html
